/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSaleRouteImport } from './routes/_app/sale'
import { Route as AppReturnRouteImport } from './routes/_app/return'
import { Route as AppMySalesRouteImport } from './routes/_app/my-sales'
import { Route as AppMyDraftsRouteImport } from './routes/_app/my-drafts'
import { Route as AppManualRouteImport } from './routes/_app/manual'
import { Route as AppIntakeRouteImport } from './routes/_app/intake'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSaleRoute = AppSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnRoute = AppReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => AppRoute,
} as any)
const AppMySalesRoute = AppMySalesRouteImport.update({
  id: '/my-sales',
  path: '/my-sales',
  getParentRoute: () => AppRoute,
} as any)
const AppMyDraftsRoute = AppMyDraftsRouteImport.update({
  id: '/my-drafts',
  path: '/my-drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppManualRoute = AppManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/intake': typeof AppIntakeRoute
  '/manual': typeof AppManualRoute
  '/my-drafts': typeof AppMyDraftsRoute
  '/my-sales': typeof AppMySalesRoute
  '/return': typeof AppReturnRoute
  '/sale': typeof AppSaleRoute
  '/search': typeof AppSearchRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/intake': typeof AppIntakeRoute
  '/manual': typeof AppManualRoute
  '/my-drafts': typeof AppMyDraftsRoute
  '/my-sales': typeof AppMySalesRoute
  '/return': typeof AppReturnRoute
  '/sale': typeof AppSaleRoute
  '/search': typeof AppSearchRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/intake': typeof AppIntakeRoute
  '/_app/manual': typeof AppManualRoute
  '/_app/my-drafts': typeof AppMyDraftsRoute
  '/_app/my-sales': typeof AppMySalesRoute
  '/_app/return': typeof AppReturnRoute
  '/_app/sale': typeof AppSaleRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/intake'
    | '/manual'
    | '/my-drafts'
    | '/my-sales'
    | '/return'
    | '/sale'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/intake'
    | '/manual'
    | '/my-drafts'
    | '/my-sales'
    | '/return'
    | '/sale'
    | '/search'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/intake'
    | '/_app/manual'
    | '/_app/my-drafts'
    | '/_app/my-sales'
    | '/_app/return'
    | '/_app/sale'
    | '/_app/search'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sale': {
      id: '/_app/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof AppSaleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/return': {
      id: '/_app/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof AppReturnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-sales': {
      id: '/_app/my-sales'
      path: '/my-sales'
      fullPath: '/my-sales'
      preLoaderRoute: typeof AppMySalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-drafts': {
      id: '/_app/my-drafts'
      path: '/my-drafts'
      fullPath: '/my-drafts'
      preLoaderRoute: typeof AppMyDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manual': {
      id: '/_app/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof AppManualRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake': {
      id: '/_app/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIntakeRoute: typeof AppIntakeRoute
  AppManualRoute: typeof AppManualRoute
  AppMyDraftsRoute: typeof AppMyDraftsRoute
  AppMySalesRoute: typeof AppMySalesRoute
  AppReturnRoute: typeof AppReturnRoute
  AppSaleRoute: typeof AppSaleRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIntakeRoute: AppIntakeRoute,
  AppManualRoute: AppManualRoute,
  AppMyDraftsRoute: AppMyDraftsRoute,
  AppMySalesRoute: AppMySalesRoute,
  AppReturnRoute: AppReturnRoute,
  AppSaleRoute: AppSaleRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
